// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFerias.Infrastructure.Data;

#nullable disable

namespace SistemaFerias.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626123026_AddExchangeAutoReplyBackup")]
    partial class AddExchangeAutoReplyBackup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaFerias.Domain.Entities.ExchangeAutoReplyBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BackupRestaurado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataBackup")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRestauracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalAudience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ExternalReply")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FeriasId")
                        .HasColumnType("int");

                    b.Property<string>("InternalReply")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoginAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FeriasId")
                        .IsUnique();

                    b.ToTable("ExchangeAutoReplyBackups");
                });

            modelBuilder.Entity("SistemaFerias.Domain.Entities.Ferias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DELETED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEntradaFerias")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFinalizacaoFerias")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRetorno")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoginAd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ferias");
                });

            modelBuilder.Entity("SistemaFerias.Domain.Entities.ExchangeAutoReplyBackup", b =>
                {
                    b.HasOne("SistemaFerias.Domain.Entities.Ferias", "Ferias")
                        .WithOne()
                        .HasForeignKey("SistemaFerias.Domain.Entities.ExchangeAutoReplyBackup", "FeriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ferias");
                });
#pragma warning restore 612, 618
        }
    }
}
